/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TipitGUI.java
 *
 * Created on Sep 22, 2011, 9:31:57 PM
 */

package wildfirecybernetics;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Currency;
import java.util.Locale;

/**
 *
 * @author Tony
 */
public class TipitGUI extends javax.swing.JFrame {

    private GratuityCalculator _calc;
    /** Creates new form TipitGUI */
    public TipitGUI() {
        initComponents();
        Money.init(Currency.getInstance(Locale.US), RoundingMode.HALF_EVEN);
        _calc = new GratuityCalculator();
        BigDecimal bd = new BigDecimal(_serviceQuality.getValue());
        bd = bd.divide(new BigDecimal("100"));
        _calc.GetCurrentEncounter().get_check().SetGratuityPercentage(bd);
    }

    private void RefreshDisplay() {
        Money mtip = _calc.GetCurrentEncounter().get_check().GetGratuityAmount();
        _totalTip.setText(mtip.toString());

        Money mperPerson = mtip.div(((Integer) _numberOfGuests.getValue()));
        _tipPerPerson.setText(mperPerson.toString());

        _total.setText(_calc.GetCurrentEncounter().get_check().GetTotalPlusGratuity().toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        _numberOfGuests = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        _serviceQuality = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _billTotal = new javax.swing.JFormattedTextField();
        _billDeductions = new javax.swing.JFormattedTextField();
        _tax = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        _tipRate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        _totalTip = new javax.swing.JFormattedTextField();
        _tipPerPerson = new javax.swing.JFormattedTextField();
        _total = new javax.swing.JFormattedTextField();
        _tipTailoring = new javax.swing.JButton();
        _configureTipItems = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipit!");
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Number of Guests");

        _numberOfGuests.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        _numberOfGuests.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                _numberOfGuestsStateChanged(evt);
            }
        });
        _numberOfGuests.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                _numberOfGuestsPropertyChange(evt);
            }
        });

        jLabel2.setText("Service Quality");

        _serviceQuality.setMajorTickSpacing(10);
        _serviceQuality.setMinorTickSpacing(1);
        _serviceQuality.setPaintLabels(true);
        _serviceQuality.setPaintTicks(true);
        _serviceQuality.setSnapToTicks(true);
        _serviceQuality.setValue(15);
        _serviceQuality.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        _serviceQuality.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                _serviceQualityStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_serviceQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_numberOfGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_numberOfGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_serviceQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Bill Total");

        jLabel4.setText("Bill Deductions");

        jLabel5.setText("Tax");

        _billTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        _billTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _billTotal.setText("0.00");
        _billTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _billTotalFocusLost(evt);
            }
        });

        _billDeductions.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        _billDeductions.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _billDeductions.setText("0.00");
        _billDeductions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _billDeductionsFocusLost(evt);
            }
        });

        _tax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        _tax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _tax.setText("0.00");
        _tax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _taxFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_tax)
                    .addComponent(_billTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(_billDeductions))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(_billTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(_billDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Tip Rate");

        _tipRate.setEditable(false);
        _tipRate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _tipRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        _tipRate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                _tipRatePropertyChange(evt);
            }
        });

        jLabel7.setText("Total Tip");

        jLabel8.setText("Tip per Person");

        jLabel9.setText("Total (Bill and Tip)");

        _totalTip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        _totalTip.setEditable(false);
        _totalTip.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        _totalTip.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        _tipPerPerson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        _tipPerPerson.setEditable(false);
        _tipPerPerson.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        _tipPerPerson.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        _total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        _total.setEditable(false);
        _total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        _total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(_tipRate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(_totalTip, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(_tipPerPerson, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(_total, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))))
                    .addComponent(jLabel9))
                .addGap(106, 106, 106))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(_tipRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(_totalTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(_tipPerPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        _tipTailoring.setText("Tip Tailoring");

        _configureTipItems.setText("Configure Tip Items");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(_tipTailoring, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_configureTipItems, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_tipTailoring)
                    .addComponent(_configureTipItems))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _numberOfGuestsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event__numberOfGuestsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event__numberOfGuestsPropertyChange

    private void _numberOfGuestsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event__numberOfGuestsStateChanged
        // TODO add your handling code here:
        Integer n = (Integer) _numberOfGuests.getValue();
        RefreshDisplay();
    }//GEN-LAST:event__numberOfGuestsStateChanged

    private void _serviceQualityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event__serviceQualityStateChanged
        // TODO add your handling code here:
        _tipRate.setText(_serviceQuality.getValue() + "%");
        
        BigDecimal bd = new BigDecimal(_serviceQuality.getValue());
        bd = bd.divide(new BigDecimal("100"));
        _calc.GetCurrentEncounter().get_check().SetGratuityPercentage(bd);
       RefreshDisplay();
    }//GEN-LAST:event__serviceQualityStateChanged

    private void _tipRatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event__tipRatePropertyChange
        // TODO add your handling code here:
        Integer n = (Integer) _serviceQuality.getValue();
        _tipRate.setText(n.toString() + "%");
    }//GEN-LAST:event__tipRatePropertyChange

    private void _billTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__billTotalFocusLost
        // TODO add your handling code here:
        String s = _billTotal.getText();
        Money billTotal = new Money(new BigDecimal(s));
        _calc.GetCurrentEncounter().get_check().SetTotal(billTotal);
       RefreshDisplay();
    }//GEN-LAST:event__billTotalFocusLost

    private void _billDeductionsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__billDeductionsFocusLost
        // TODO add your handling code here:
        String s = _billDeductions.getText();
        Money billDeductions = new Money(new BigDecimal(s));
        _calc.GetCurrentEncounter().get_check().SetDeductions(billDeductions);
       RefreshDisplay();
    }//GEN-LAST:event__billDeductionsFocusLost

    private void _taxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__taxFocusLost
        // TODO add your handling code here:
        String s = _tax.getText();
        Money tax = new Money(new BigDecimal(s));
        _calc.GetCurrentEncounter().get_check().SetDeductions(tax);
       RefreshDisplay();
    }//GEN-LAST:event__taxFocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipitGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField _billDeductions;
    private javax.swing.JFormattedTextField _billTotal;
    private javax.swing.JButton _configureTipItems;
    private javax.swing.JSpinner _numberOfGuests;
    private javax.swing.JSlider _serviceQuality;
    private javax.swing.JFormattedTextField _tax;
    private javax.swing.JFormattedTextField _tipPerPerson;
    private javax.swing.JTextField _tipRate;
    private javax.swing.JButton _tipTailoring;
    private javax.swing.JFormattedTextField _total;
    private javax.swing.JFormattedTextField _totalTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
